[project]
name = "sk-website"
version = "0.3.0"
description = "This is the source code for my personal website."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "commitizen>=4.8.3",
    "dj-database-url>=2.0.0",
    "django>=4.0.0",
    "django-bootstrap-v5>=1.0.11",
    "gunicorn>=20.1.0",
    "psycopg2-binary>=2.9.0",
    "pytest>=8.4.1",
    "python-dotenv>=1.0.0",
    "whitenoise>=6.0.0",
]

[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "$version"
version_scheme = "pep440"
version_provider = "uv"
update_changelog_on_bump = true
major_version_zero = true
