"""
Django settings for sk project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Load environment variables from .env file (development only)
try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    # dotenv not available in production, which is fine
    pass

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ["DJANGO_SECRET_KEY"]

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "False") == "True"

# For initial debugging in production, temporarily enable more verbose error reporting
# Remove this after deployment is working
if not DEBUG:
    ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", "").split(",")
    # Temporarily enable logging for deployment debugging
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'handlers': {
            'console': {
                'class': 'logging.StreamHandler',
            },
        },
        'loggers': {
            'django': {
                'handlers': ['console'],
                'level': 'INFO',
            },
        },
    }

ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", "").split(",")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bootstrap5',
    'home',
    'sk',
    'projects',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Add security middleware for production
if not DEBUG:
    # Add additional security middleware in production
    pass  # SecurityMiddleware is already included

ROOT_URLCONF = 'sk.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'sk', 'templates'),
            os.path.join(BASE_DIR, 'home', 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sk.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Database configuration with PostgreSQL for both development and production
def get_database_config():
    """
    Returns PostgreSQL database configuration for both development and production.
    Priority order:
    1. DATABASE_URL (production environments like Render, Heroku)
    2. Manual PostgreSQL configuration with environment variables
    3. Default PostgreSQL settings for development
    """
    
    # First try DATABASE_URL (for production environments)
    database_url = os.environ.get("DATABASE_URL")
    if database_url:
        import dj_database_url
        return {'default': dj_database_url.parse(database_url)}
    
    # PostgreSQL configuration (for both dev and production)
    return {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('DB_NAME', 'sk_website'),
            'USER': os.environ.get('DB_USER', 'postgres'),
            'PASSWORD': os.environ.get('DB_PASSWORD', ''),
            'HOST': os.environ.get('DB_HOST', 'localhost'),
            'PORT': os.environ.get('DB_PORT', '5432'),
            'OPTIONS': {
                'connect_timeout': 10,
            },
        }
    }

DATABASES = get_database_config()

# Add connection timeout and retry logic for PostgreSQL
if DATABASES['default']['ENGINE'] == 'django.db.backends.postgresql':
    DATABASES['default'].setdefault('OPTIONS', {})
    DATABASES['default']['OPTIONS'].update({
        'connect_timeout': 10,
        # Remove the problematic default_transaction_isolation setting
    })


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'sk', 'static'),
    os.path.join(BASE_DIR, 'home', 'static'),
]

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Whitenoise configuration for static files
# Use CompressedStaticFilesStorage instead of CompressedManifestStaticFilesStorage 
# to avoid manifest entry issues in production
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

# WhiteNoise settings for better performance
WHITENOISE_USE_FINDERS = os.environ.get("WHITENOISE_USE_FINDERS", "True") == "True"
WHITENOISE_AUTOREFRESH = os.environ.get("WHITENOISE_AUTOREFRESH", "True") == "True"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# HTTPS/SSL Configuration
# Force HTTPS in production
SECURE_SSL_REDIRECT = os.environ.get("SECURE_SSL_REDIRECT", "False") == "True"

# HSTS (HTTP Strict Transport Security) settings
SECURE_HSTS_SECONDS = int(os.environ.get("SECURE_HSTS_SECONDS", "0"))
SECURE_HSTS_INCLUDE_SUBDOMAINS = os.environ.get("SECURE_HSTS_INCLUDE_SUBDOMAINS", "False") == "True"
SECURE_HSTS_PRELOAD = os.environ.get("SECURE_HSTS_PRELOAD", "False") == "True"

# Secure cookies
SESSION_COOKIE_SECURE = os.environ.get("SESSION_COOKIE_SECURE", "False") == "True"
CSRF_COOKIE_SECURE = os.environ.get("CSRF_COOKIE_SECURE", "False") == "True"

# Additional security settings for production
if not DEBUG:
    # Force secure settings in production if not explicitly set
    SECURE_SSL_REDIRECT = SECURE_SSL_REDIRECT or True
    SECURE_HSTS_SECONDS = SECURE_HSTS_SECONDS or 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = SECURE_HSTS_INCLUDE_SUBDOMAINS or True
    SECURE_HSTS_PRELOAD = SECURE_HSTS_PRELOAD or True
    SESSION_COOKIE_SECURE = SESSION_COOKIE_SECURE or True
    CSRF_COOKIE_SECURE = CSRF_COOKIE_SECURE or True
    
    # Additional production security
    SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
    SECURE_CROSS_ORIGIN_OPENER_POLICY = 'same-origin'

# Secure proxy headers (important for deployment platforms like Render, Heroku, etc.)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Content security settings
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
X_FRAME_OPTIONS = 'DENY'

# CSRF Settings
CSRF_TRUSTED_ORIGINS = []

# Production domains - Update these with your actual domains
if not DEBUG:
    CSRF_TRUSTED_ORIGINS.extend([
        'https://syafiqkay.com',
        'https://www.syafiqkay.com',
        # Add your actual production domains here
    ])
else:
    # Development domains
    CSRF_TRUSTED_ORIGINS.extend([
        'http://localhost:8000',
        'http://127.0.0.1:8000',
        'http://0.0.0.0:8000',
        'https://localhost:8000',
        'https://127.0.0.1:8000',
    ])

# Add environment-specific domains from ALLOWED_HOSTS
for host in ALLOWED_HOSTS:
    if host and '*' not in host and host not in ['localhost', '127.0.0.1', '0.0.0.0']:
        # Add both HTTP and HTTPS for each host
        if DEBUG:
            CSRF_TRUSTED_ORIGINS.extend([
                f'http://{host}',
                f'https://{host}',
            ])
        else:
            # Production - only HTTPS
            CSRF_TRUSTED_ORIGINS.append(f'https://{host}')

# Handle wildcard domains (for development environments like Codespaces, Gitpod)
if DEBUG:
    for host in ALLOWED_HOSTS:
        if '*' in host:
            if '*.gitpod.io' in host:
                CSRF_TRUSTED_ORIGINS.extend([
                    'https://*.gitpod.io',
                    'http://*.gitpod.io',
                ])
            if '*.github.dev' in host:
                CSRF_TRUSTED_ORIGINS.extend([
                    'https://*.github.dev',
                    'http://*.github.dev',
                ])
            if '*.codespaces.githubusercontent.com' in host:
                CSRF_TRUSTED_ORIGINS.extend([
                    'https://*.codespaces.githubusercontent.com',
                ])

# Login/Logout URLs
LOGIN_URL = '/admin/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'
