# Generated by Django 4.2.26 on 2025-11-27 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WorkingIdentity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identity",
                    models.CharField(
                        choices=[
                            ("pharmacy", "Pharmacy"),
                            ("law", "Law"),
                            ("cybersecurity", "Cybersecurity"),
                            ("actuary", "Actuary"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="e.g., 'Foundation identity', 'Study phase'",
                        max_length=200,
                    ),
                ),
                (
                    "experiment_plan",
                    models.TextField(
                        help_text="Aim, hypothesis, methods of this working identity test"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Working Identities",
                "ordering": ["identity"],
            },
        ),
        migrations.CreateModel(
            name="IdentityFeed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("status", models.TextField()),
                ("next_action", models.TextField()),
                ("notes", models.TextField(blank=True)),
                (
                    "working_identity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feed_entries",
                        to="portfolio.workingidentity",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Identity Feed Entries",
                "ordering": ["-date"],
            },
        ),
    ]
